import { Dimensions, StyleSheet } from 'react-native'
const styles = StyleSheet.create({
  imageBackgroundContainer: {
    flex: 1,
  },
  touchableStyle: {
    backgroundColor: '#B6C4E6',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 20,
    width: '65%',
    height: '10%',
    borderRadius: 10,
  },
  textStyle: {
    color: '#39559E',
    fontWeight: 'bold',
    color: 'silver',
    fontFamily: 'Iowan Old Style',
  },
  inputStyle: {
    backgroundColor: '#B6C4E6',
    fontSize: 15,
    color: '#39559E',
    marginBottom: 25,
    marginHorizontal: 45,
    paddingLeft: 15,
    height: 55,
    borderRadius: 10
  },
  inputStyle1: {
    backgroundColor: '#B6C4E6',
    fontSize: 15,
    color: '#39559E',
    marginBottom: 10,
    marginHorizontal: 45,
    paddingLeft: 15,
    height: 55,
    borderRadius: 10
  },
  container: {
    backgroundColor: '#A68D80',
    fontSize: 20,
    color: '#BACED8',
    marginTop: 35,
    height: 55,
    width: 300,
    borderRadius: 10,
    alignSelf: 'center',
    paddingLeft: 20,
    fontFamily: 'Iowan Old Style',
  },
  container1: {
    fontSize: 20,
    color: '#6080D1',
    alignSelf: 'center',
    paddingVertical: 12
  },
  container2: {

    justifyContent: 'center',
    alignItems: 'center',
    // alignSelf: 'center',
    fontSize: 25,
    color: '#6080D1',
    fontFamily: 'Iowan Old Style'
  },
  container3: {
    backgroundColor: '#B6C4E6',
    fontSize: 20,
    color: '#6080D1',
    marginTop: 150,
    height: 45,
    width: 150,
    borderRadius: 10,
    alignSelf: 'center'
  },
  container4: {
    backgroundColor: '#183E9F',
    fontSize: 20,
    color: '#BACED8',
    marginTop: 5,
    height: 100,
    Width: 1000,
    borderRadius: 0,
    alignSelf: 'center',
    paddingLeft: 20,
    textAlign: 'center',

  },
  container5: {
    fontSize: 20,
    color: '#BACED8',
    width: "100%",
    marginVertical: "1%",
    borderRadius: 0,
    alignSelf: 'center',
    textAlign: 'center',

  },
  container6: {
    backgroundColor: '#C1C1C1',
    fontSize: 20,
    color: '#BACED8',
    marginTop: 5,
    height: 70,
    Width: 80,
    borderRadius: 10,
    alignSelf: 'flex-start',
    paddingLeft: 20,
    textAlign: 'center',

  },

  container7: {
    //backgroundColor: '#183E9F',
    fontSize: 20,
    color: '#BACED8',
    marginTop: 10,
    height: '40%',
    width: 300,
    borderRadius: 10,
    alignSelf: 'center',
    paddingLeft: 20,
    fontFamily: 'Iowan Old Style',
  },
  container8: {
    backgroundColor: '#808977',
    fontSize: 20,
    color: '#BACED8',
    marginTop: 10,
    height: '80%',
    width: 300,
    borderRadius: 10,
    alignSelf: 'center',
    paddingLeft: 20,
    fontFamily: 'Iowan Old Style',
  },
  container9: {
    backgroundColor: '#808977',
    fontSize: 20,
    color: '#BACED8',
    marginTop: 10,
    height: '95%',
    width: 300,
    borderRadius: 10,
    alignSelf: 'center',
    paddingLeft: 20,
    fontFamily: 'Iowan Old Style',
  },
  DpView: {
    backgroundColor: '#B6C4E6',
    height: 150,
    width: 150,
    borderRadius: 200,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: '10%',
    marginBottom: 50,
  },
  MainContainer:
  {
    flex: 1,
    // alignSelf: 'center',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#DBE6E4',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height
    // width: '100%',
    // height: '100%',
    // resizeMode: 'cover',
  },
  

  touchableStyle2: {
    //backgroundColor:'rgba(83, 110, 115, 0.6)',
    marginTop: 10,
    //marginLeft:10,
    width: 180,
    height: 70,
    borderRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
  },
  touchableStyle3: {
    //backgroundColor:'rgba(83, 110, 115, 0.6)',
    marginTop: 10,
    marginLeft: 8,
    width: 180,
    height: 70,
    borderRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
  }
})
export { styles }